services:
  assemble:
    image: reproducible-molly
    build:
      context: ..
    command: :app:assembleRelease :app:bundleRelease --no-daemon
    volumes:
      - ./certs:/molly/app/certs:ro
      - ./outputs:/molly/app/build/outputs
    environment:
      - GRADLE_OPTS
      - CI_APP_TITLE
      - CI_APP_FILENAME
      - CI_PACKAGE_ID
      - CI_BUILD_VARIANTS
      - CI_FORCE_INTERNAL_USER_FLAG
      - CI_MAPS_API_KEY
      - CI_KEYSTORE_PATH
      - CI_KEYSTORE_PASSWORD
      - CI_KEYSTORE_ALIAS

  keystore:
    image: reproducible-molly
    build:
      context: ..
    entrypoint: ["/bin/sh", "-c"]
    command: ["keytool -genkey -v -keystore /molly/app/certs/osCASH-release.keystore -alias oscash-key -keyalg RSA -keysize 2048 -validity 10000 -storepass 'osCASH2025Release!' -keypass 'osCASH2025Release!' -dname 'CN=osCASH.me, OU=osCASH Development, O=osCASH.me, L=Blockchain, S=Crypto, C=WW'"]
    volumes:
      - ./certs:/molly/app/certs
